# Encontro 9 - Homework: Distribuições de probabilidade
Temos quatro amostras aleatórias, identificadas como colunas `A`, `B`, `C` e `D` em um DataFrame.

Os parâmetros das distribuições que geraram essas amostras são `"desconhecidos"`.
Seu objetivo será investigar os dados e formular hipóteses sobre essas
distribuições.

## 1. Carregando os dados do repositório
Execute a célula abaixo para importar as bibliotecas e carregar o as amostras.

In [19]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [20]:
amostras_url = (
    "https://raw.githubusercontent.com/jhlopesalves/eda_humanidades/"
    "refs/heads/main/encontro_9/homework/amostras.csv"
)

amostras = pd.read_csv(amostras_url)

## 2. Inspeção inicial dos dados

1. Inspecione 10 linhas aleatórias do DataFrame.
2. Verifique o número de linhas e colunas.
3. Identifique as amostras disponíveis.

In [21]:
# Inspecione 10 linhas aleatórias.

amostras

             A          B          C          D
0    10.609434  17.727724   9.703587   8.867410
1     7.920032  16.790370   6.353565   8.750793
2    11.500902  13.561040   7.927635  12.650293
3    11.881129  11.994993  13.169552  10.660580
4     6.097930   9.070942  10.014966   9.576532
..         ...        ...        ...        ...
495  11.871094  15.705440   4.480057  10.784022
496   6.337188  16.533646  11.613987  10.607675
497   9.328785  15.242356   4.249573   9.816920
498   6.018376  15.261528  13.559885   8.938356
499   7.009878  16.647506   4.092605  14.428305

[500 rows x 4 columns]

## 3. Estatísticas de tendência central

Obtenha um resumo estatístico das quatro amostras.

Observe especialmente:

- média;
- desvio-padrão;
- mediana;
- primeiro e terceiro quartis.

> Hint: É possível obter o resumo utilizando apenas **um único método**

In [22]:
# Obtenha um resumo estatístico das quatro amostras

amostras.describe().round(2).T

   count   mean   std   min    25%    50%    75%    max
A  500.0   9.97  1.92  4.87   8.67  10.01  11.17  15.83
B  500.0  14.91  2.04  7.70  13.55  15.02  16.19  21.36
C  500.0   9.98  5.11 -4.78   6.69  10.02  13.28  24.05
D  500.0   9.68  2.01  3.90   8.42   9.73  11.02  15.83

### Comparando as estatísticas

Com base no resumo estatístico:

1. Quais amostras apresentam médias semelhantes?
2. Quais apresentam desvios-padrão semelhantes?
3. Há alguma amostra que se destaca por apresentar maior dispersão?

Escreva uma resposta curta.

RESPOSTA: _(clique duas vezes para editar e escrever sua resposta)_

## 4. Visualização das distribuições

Compare as quatro amostras utilizando uma ECDF.

O gráfico deve:

1. representar as quatro amostras no mesmo eixo;
2. identificar cada amostra na legenda;
3. incluir título e rótulos para os eixos.

dica: lembre-se que no encontro utilizamos o parametro "data" com o nome do DataFrame ao invés de data=DataFrame, x="coluna e y="coluna.

In [36]:
# Construa uma ECDF comparando as quatro amostras.

Represente agora as mesmas quatro amostras utilizando histogramas.

Mantenha as quatro distribuições no mesmo gráfico para facilitar a comparação.

dica: `bins="fd"`, `fill=True`, `common_norm=False`... se estes argumentos não soam familiares, dê uma olhada na documentação [Seaborn: histplot](https://seaborn.pydata.org/generated/seaborn.histplot.html); ou no [notebook do encontro 9](https://github.com/jhlopesalves/eda_humanidades/blob/main/encontro_9/enc_9.ipynb).

In [35]:
# Construa um histograma comparando as quatro amostras.

### Comparação das visualizações

Com base nas ECDFs e KDEs:

1. Quais amostras apresentam posições semelhantes?
2. Quais apresentam dispersões semelhantes?
3. As conclusões obtidas pelos dois gráficos são consistentes entre si?

Justifique brevemente.

RESPOSTA: _(clique duas vezes para editar e escrever sua resposta)_